{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wm-um-pdb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: wm-um
    component: messaging
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: wm-um
{{- end }}
